name: CI/CD

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4.1.7

            - name: Set Up Node.js
              uses: actions/setup-node@v4.0.3
              with:
                  node-version: '22.7.0'

            - name: Install Dependencies
              run: npm ci

            - name: Lint and Test
              run: npm run lint

            - name: Build
              run: npm run build

            - name: Create Changeset
              uses: changesets/action@v1.4.8
              with:
                  commit: true # Set to true if you want the action to commit the changeset
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Version Packages
              run: npm run changeset-version

            - name: Publish Package
              run: npm run changeset-publish
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
